version: 2.1

orbs:
  test: reactiveops/test@dev:master

jobs:
  build:
    docker:
      - image: "quay.io/reactiveops/ci-images:v8.0-alpine"
    steps:
      - test/set_env
      - checkout
      - run:
          name: Docker Login
          command: |
            docker login -u="reactiveops+circleci" -p="${quay_token}" quay.io
      - test/docker_build:
          config: deploy/build.config
  push:
    docker:
      - image: "quay.io/reactiveops/ci-images:v8.0-alpine"
    steps:
      - test/set_env
      - checkout
      - run:
          name: Docker Login
          command: |
            docker login -u="reactiveops+circleci" -p="${quay_token}" quay.io
      - test/docker_push:
          config: deploy/build.config

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only: master
      - build:
          context: org-global
          filters:
            branches:
              only: master
