version: 2.1

orbs:
  rok8s: fairwinds/rok8s-scripts@8.1.0

workflows:
  build_and_push:
    jobs:
      - rok8s/docker_build_and_push:
          config_file: deploy/build.config
          docker-login: true
          username: "reactiveops+circleci"
          registry: "quay.io"
          password-variable: fairwinds_quay_token
          context: org-global
          filters:
            branches:
              only: master
