version: 2.1

orbs:
  test: reactiveops/test@dev:master

jobs:
  build:
    docker:
      - image: "quay.io/reactiveops/ci-images:v8.0-alpine"
    steps:
      - test/set_env
      - checkout
      - test/docker_build:
          config: deploy/build.config

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
