version: 2.1

orbs:
  rok8s: reactiveops/rok8s-scripts@dev:sudermanjr/orbs

workflows:
  build_and_push:
    jobs:
      - rok8s/docker_build_and_push:
          config_file: deploy/build.config
          docker-login: true
          username: "reactiveops+circleci"
          registry: "quay.io"
          password-variable: quay_token
          filters:
            branches:
              only: master
