version: 2.1

orbs:
  test: reactiveops/test@dev:master

jobs:
  hellojob:
    docker:
      - image: "quay.io/reactiveops/ci-images:v8.0-alpine"
    steps:
      - test/set_env
      - test/hello:
          username: "Groot"
      - run:
          name: env
          command: env

workflows:
  version: 2
  build:
    jobs:
      - hellojob:
          filters:
            branches:
              only: /.*/
