version: 2.1

orbs:
  test: reactiveops/test@dev:master

jobs:
  hellojob:
    docker:
      - image: "quay.io/reactiveops/ci-images:v8.0-alpine"
    steps:
      - test/hello:
          username: "Groot"
