apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: circleci
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - list
  - get
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  verbs:
  - list
