apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: andrew@suderman.us.com
    dns01:
      providers:
        - name: cloudflare
          cloudflare:
            email: andrew@suderman.us.com
            apiKeySecretRef:
              name: cloudflare-api-key-secret
              key: api-key
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
