apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: rbac-manager-definition
  namespace: kube-system
rbacBindings:
  - name: circleci
    subjects:
      - kind: ServiceAccount
        name: circleci
        namespace: helm-system
    roleBindings:
      - clusterRole: tiller-user
        namespace: helm-system
      - clusterRole: cluster-admin
        namespaceSelector:
          matchLabels:
            circleci-admin: "yes"
    clusterRoleBindings:
      - clusterRole: circleci
