apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: dockersamples/examplevotingapp_worker
        name: worker
        resources:
          limits:
            cpu: 1100m
            memory: 500Mi
          requests:
            cpu: 1100m
            memory: 450Mi
