apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "load-generator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "load-generator.name" . }}
    helm.sh/chart: {{ include "load-generator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "load-generator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "load-generator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          #command: ["k6", "run", "/k6/load.js"]
          command: ["sleep", "10000"]
          #args: ["--out", "influxdb"]
          env:
            - name: K6_DURATION
              value: "0"
            - name: K6_RPS
              value: "1"
            - name: K6_VUS_MAX
              value: "1"
            - name: K6_VUS
              value: "1"
            - name: INFLUXDB_DB
              value: k6
            - name: INFLUXDB_INSECURE
              value: "true"
            - name: INFLUXDB_ADDR
              value: "http://data-influxdb.tick:8086"
            - name: INFLUXDB_RETENTION
              value: autogen
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
          - name: k6files
            mountPath: /k6
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: k6files
          configmap:
            name: {{ include "load-generator.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
