apiVersion: linkerd.io/v1alpha1
kind: ServiceProfile
metadata:
  name: {{ include "basic-demo.fullname" . }}
spec:
  routes:
  - name: '/ping'
    condition:
      pathRegex: '/ping'
      method: GET
    isRetryable: true
    responseClasses:
    - condition:
        status:
          min: 500
          max: 599
      isFailure: true
      timeout: 250ms
