apiVersion: linkerd.io/v1alpha1
kind: ServiceProfile
metadata:
  name: {{ include "basic-demo.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
spec:
  routes:
  - name: 'GET /ping'
    condition:
      pathRegex: '/ping'
      method: GET
